# Generated by Django 4.1.5 on 2023-01-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whale',
            old_name='verified_artist',
            new_name='verified_whale',
        ),
    ]
